site_name: Documentation
nav:
    - Quick Start: index.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
