site_name: Documentation
nav:
    - Home: index.md
    - Quick Start:
        - ODM: quickstart/odm.md
        - Migrations: quickstart/migrations.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
