site_name: Documentation
nav:
    - Introduction: index.md
    - Document: document.md
    - Init: init.md
    - Create: insert.md
    - Find: find.md
    - Update: update.md
    - Delete: delete.md
    - Aggregate: aggregate.md
    - Api:
        Document:  api/document.md
        Query: api/queries.md
        Interfaces: api/interfaces.md
        Operators:
            Find: api/operators/find.md
            Update: api/operators/update.md
        Fields: api/fields.md
    - Migrations: migrations.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
