site_name: Documentation
nav:
    - Introdution: index.md
    - Tutorial: tutorial.md
    - Api:
        Document:  api/document.md
        Query: api/queries.md
        Interfaces: api/interfaces.md
        Operators:
            Find: api/operators/find.md
            Update: api/operators/update.md
    - Migrations: migrations.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
