site_name: Documentation
nav:
    - Home: index.md
    - Tutorial:
        - ODM: tutorial/odm.md
        - Migrations: tutorial/migrations.md
    - Documentation:
        - ODM:  documentation/odm.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
