name: Lint
on: [ pull_request ]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.9 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: ruff install
        run: pip3 install ruff
      - name: lint
        run: ruff beanie/ tests/