name: Publish project
on:
  push:
    branches:
      - main
jobs:
  publish_project:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install flit
        run: pip install flit
      - name: build
        run: flit build
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1